#version: '3.8'

services:
  mongodb:
    image: mongodb/mongodb-community-server:5.0-ubuntu2004
    container_name: mongodb
    ports:
      - "27017:27017"
    env_file:
      - .env
    environment:
      TZ: "Europe/Madrid"
      MONGO_INITDB_ROOT_USERNAME: "${DB_ROOT_USER}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_ROOT_PASS}"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
      # - ./data:/data/db
    restart: unless-stopped
    mem_limit: 256m
    cpus: 0.5

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    env_file:
      - .env
    environment:
      TZ: "Europe/Madrid"
      ME_CONFIG_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_URL: "mongodb://${DB_ROOT_USER}:${DB_ROOT_PASS}@mongodb:27017"
      ME_CONFIG_BASICAUTH: "false"
      # ME_CONFIG_BASICAUTH_ENABLED: "false"
      ME_CONFIG_REQUEST_SIZE:	"1mb"
      ME_CONFIG_OPTIONS_CONFIRM_DELETE: "true"
    depends_on:
      - mongodb
    restart: unless-stopped
    mem_limit: 128m
    cpus: 0.25
